# Generated by Django 4.1.5 on 2023-02-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0003_alter_categories_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='url'),
        ),
    ]
