# Generated by Django 4.1.5 on 2023-02-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0004_categories_slug_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
    ]
