# Generated by Django 4.1.5 on 2023-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0005_remove_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
