# Generated by Django 4.1.5 on 2023-02-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
        ('BLOG', '0008_remove_question_author_question_author_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='who_see_post',
            field=models.ManyToManyField(to='users.profile'),
        ),
    ]
